//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Access {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Access.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know.. something cool I guess..
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client is already registered..
        /// </summary>
        public static string ClientAlreadyRegistered {
            get {
                return ResourceManager.GetString("ClientAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /client is used to Register Client Applications with Core.Access Provider..
        /// </summary>
        public static string ClientIndexMessage {
            get {
                return ResourceManager.GetString("ClientIndexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Client {@Name} has been registered successfully. Please remember your password for Basic Authentication with Core.Access. Your unique Client Id is @ClientId.
        /// </summary>
        public static string ClientRegisteredSuccess {
            get {
                return ResourceManager.GetString("ClientRegisteredSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth provided is incorrect or invalid. .
        /// </summary>
        public static string DateOfBirthIncorrect {
            get {
                return ResourceManager.GetString("DateOfBirthIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re quite old G. .
        /// </summary>
        public static string DateOfBirthTooOld {
            get {
                return ResourceManager.GetString("DateOfBirthTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re too young kiddo..
        /// </summary>
        public static string DateOfBirthTooYoung {
            get {
                return ResourceManager.GetString("DateOfBirthTooYoung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only &apos;code&apos; flow is enabled. Please select appropriate response_type..
        /// </summary>
        public static string OnlyAuthorizeCodeFlowEnabled {
            get {
                return ResourceManager.GetString("OnlyAuthorizeCodeFlowEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RefreshValue should change everytime the refresh token flow is invoked.
        /// </summary>
        public static string RefreshDesc {
            get {
                return ResourceManager.GetString("RefreshDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /oauth path is used to exchange codes &amp; tokens and validate tokens from resource servers..
        /// </summary>
        public static string ServerAuthWorking {
            get {
                return ResourceManager.GetString("ServerAuthWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Server/Security Token Service { Core.Access } is up..
        /// </summary>
        public static string ServerWorking {
            get {
                return ResourceManager.GetString("ServerWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token has expired. .
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client is not known to Authorization Server..
        /// </summary>
        public static string UnknownClient {
            get {
                return ResourceManager.GetString("UnknownClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Invalid..
        /// </summary>
        public static string UnknownUser {
            get {
                return ResourceManager.GetString("UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already registered..
        /// </summary>
        public static string UserAlreadyRegistered {
            get {
                return ResourceManager.GetString("UserAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /user is used to Register End Users with Core.Access Provider..
        /// </summary>
        public static string UserIndexMessage {
            get {
                return ResourceManager.GetString("UserIndexMessage", resourceCulture);
            }
        }
    }
}
